- layouts/partials/head.html
For sites that do not specify a title field in config, the homepage will produce code like this
```html
<title> Jane Doe |  </title>
```
which looks rather wrong, and is easily fixed. This PR changes the output to 
```html
<title> Jane Doe </title>
```
which satisfies both cases.
> Only add pipe character to page title when config is set

- README.md
- exampleSite/config.toml
- layouts/index.html
As mentioned [in the `where` docs from `hugo`](https://gohugo.io/functions/where/#mainsections) with regards to `mainSections` comparing against `.Site.Params.mainSections` allows the users to configure it on the `config.toml` like so:
```toml
[params]
mainSections = ["blog", "docs"]
```
> Make pagination sections configurable

- layouts/partials/head.html
- There were two half-width spaces, so I fixed it to one.
closes #43
> fix: fix white space in partials template

- assets/css/style.css
Hi,
you made a pretty and very lightweight theme there. Thanks for that! The only thing I was missing is styling for blockquotes. So I've added them (see pictures). I got inspired by GitHub's Markdown styling.
**Light**
**Dark**
Let me know what you think. 😄
> Add styling for blockquotes

- layouts/_default/baseof.html
- layouts/_default/list.html
- layouts/partials/footer.html
- layouts/partials/sidebar.html
Please consider:
- Footer and the base template both contained `</html>` and  `</body>`, removed
- Sidebar contained an incorrect number of divs, removed
- List was missing a closing `</ul>`
Reordered some of the files to enhance readability.
> HTML validation fixes

- README.md
- exampleSite/config.toml
- layouts/partials/head.html
Please consider the following:
- Add conditional Google Site Verification meta tag.
I used a little different conditional checking style and included the parameter in the `param` field, I hope that is okay, this is what the Hugo manual tells me to do.
> Add option to add Google Site Verification meta tag

- layouts/partials/head.html
Apologies! It turns out the `isset` with the `.Params` reference would always return false.
Fixed now 👍
> Fix googleSiteVerify

- assets/css/style.css
I added a few CSS rules that allow for the contents to be better rendered when printed.  
Short list of visual differences:
- Hid ```.page-top``` class, as it is not functional on printed paper;  
- Made the left section to be displayed vertically and only once;
Printed page, **before**:
Printed page, **after**:
> Printer friendly CSS

- README.md
- exampleSite/config.toml
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/index.html
- layouts/partials/navbar.html
- layouts/partials/sidebar.html
Very minor feature adding new config setting for animated loading making it simply optional.
The theme is awesome, I just honestly have to admit by brain refused to accept this animation.
The solution works as intended, although it requires users to specify the `animatedLoading` param setting it to `true` (this could be considered a breaking change for some folks that do not follow the commit logs and changelogs).
I'll give it another thought if you consider it somehow wrong and if there should be a better way to handle this.
> Make the animated loading an option in config file

- README.md
- exampleSite/config.toml
- layouts/partials/sidebar.html
Hi @lxndrblz ,
looking at the theme, I saw that it wasn't possible to specify more than one year for the copyright years.
For this reason, I added the possibility to configure the copyrights years under the configuration params but still having the current behaviour as default in case this configuration is not specified.
Let me know if there is something to improve.
> Added the possibility to configure the copyright years

- README.md
- assets/js/anatole-header.js
- assets/js/anatole-theme-switcher.js
- layouts/partials/head.html
- layouts/partials/navbar.html
Hi @lxndrblz ,
I was thinking that since there is the possibility to set a default theme, It could also be useful to disable the theme switcher and for this reason, I opened this PR.
I split the js files so if the theme switcher is disabled, the theme-switcher javascript will not be loaded. This will help to reduce the amount of data that should be downloaded.
I also added a brief paragraph in the documentation on how to disable it.
Let me know if there is something that could be improved.
> Added possibility to disable theme switcher

- README.md
- assets/css/style.css
- i18n/de.toml
- i18n/dk.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fa.toml
- i18n/fi.toml
- i18n/fr.toml
- i18n/it.toml
- i18n/pt-br.toml
- i18n/zh-cn.toml
- i18n/zh-tw.toml
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/index.html
- layouts/partials/contact.html
- layouts/partials/navbar.html
- layouts/partials/sidebar.html
OK both forms have been tested as working. Formspree has an optional recaptcha, Netlify has an optional recaptcha and a mandatory honeypot. I corrected css around the form inputs, reinstated the animation fade in. Formspree's redirections are no more, feedback provided at the bottom of the form. All text is internationalized. Recaptcha will reflect the theme of the website, but not if the theme switcher is used while the contact form is visible - it will show the change in the next refresh.
> Formspree, Netlify forms with spam protection.

- assets/css/markupHighlight.css
The `chr-p-color` value was missing from the dark theme section. As a result,
punctuation marks appeared unreadable when using the dark theme. According to
[Chroma's source](https://github.com/alecthomas/chroma/blob/master/styles/monokai.go),
the Monokai color for punctuation is `#f8f8f2`.
> Fix punctuation color in the dark theme syntax highlighting.

- README.md
- layouts/index.html
Thanks for creating this beautiful and minimal theme!
I wanted to have the ability to show the full content of blog posts on the home page.
Proposing parametrising that by adding the parameter `fullPostContent` to toggle between showing either the full content or the summary of posts on the home page.
Would like to contribute this upstream if it might be useful.
> Ability to show full post content on home page

- README.md
- layouts/partials/medium-zoom.html
Hi,
I wanted a way of disabling the medium zoom functionality but I didn't see any way to do that. To do this I overrode the partial in my own project but thought it made sense to see if I could get this in the main theme.
I'm new to Hugo and this is my first time contributing to any project on GitHub so apologies if something is off.
Cheers.
> Added a configuration option for the medium zoom functionality.

- README.md
- layouts/_default/single.html
Hi,
Another small config option allows the comments to be disabled on a page per page basis by including `disableComments: true` in the Front Matter of the page.
I noticed the `post.md` archetype in the theme has the `DisableComments: false` Front Matter but couldn't find any evidence of this being implemented in the past.
Cheers.
> Implemented per page comment disabling using the page Front Matter.

- layouts/partials/head.html
As Per: [Issue 153](https://github.com/lxndrblz/anatole/issues/153)
Change to meta description to use the page description Front Matter if set falling back to the site description if not.
> Change to meta description to use the pages description Front Matter

- layouts/partials/taxonomy/categories.html
- layouts/partials/taxonomy/tags.html
- layouts/partials/taxonomy/template.html
Afternoon,
Feel free to do with this as you please I just noticed the partials were incredibly similar and since the URL encoding logic had been added to both they'd benefit from having a single common parameterised partial.
Cheers.
> Tweak to taxomony partials to reduce code duplication

- README.md
- exampleSite/config.toml
- layouts/_default/single.html
This kind of works, but I'm not sure if I need to check for the parameter before comparing it to .Type, like this:
if isset .Site.Params "postSectionName"
Adding it to the if statement returns false for some reason, so I removed it and it still works. Apparently if `postSectionName` isn't defined then the following statement will return false anyway:
if eq .Site.Params.postSectionName .Type
May need more checks as I'm not very good w/ Go/Hugo code.
> Allow users to re-define post section name

- layouts/_default/list.html
- layouts/_default/single.html
- layouts/partials/head.html
- layouts/partials/medium-zoom.html
- layouts/partials/navbar.html
- layouts/partials/sidebar.html
I was going to use [ngrok](https://ngrok.com/) to forward a local dev server to my phone to test some layout things, but as some URLs were absolute instead of relative, this broke styling. So I went ahead and changed absolute URLs to relative URLs to fix this, should hopefully make hugo builds with this theme more portable for others :grin:
> Changed absolute URLs to relative

- layouts/partials/sidebar.html
Actually do so this time.
Turns out, I forgot to pipe `.Site.Params.copyright` to `markdownify`.  Whoops.
> Treat the "copyright" parameter as markdown

- README.md
- layouts/partials/sidebar.html
Document as well
See #206 and #208.  Sorry for the noise.
> Include substitution of year in user-defined copyright strings

- README.md
This adds missing favicon files info to the docs for users to know which files to provide.
> add favicon files info to docs

- README.md
- exampleSite/content/arabic/_index.md
- exampleSite/content/english/_index.md
- layouts/index.html
On my personal website I have static content in `_index.md` which I use to introduce myself. Beneath I render the posts using `mainSections`. The problem with this approach and the current theme layout is that the posts appear without context beneath the content of `_index.md`.
You might think that you could add a heading in `_index.md` as the very last content. However, using markdown the appearance just isn't right. You'd need HTML and CSS to make it look pleasing. I think this is a more common issue so that it makes sense to offer a 'native' way offered by the theme; hence I propose this PR.
> Add Option for Main Sections Heading

- assets/css/style.css
Due to the latest changes, the last navigation item of `nav__list` is not centered. This results from the padding used for the top navbar view breaking through which in turn is not applied on the last element. This PR fixes this issue by only adding paddings for the top navbar view. Futhermore, I only applied the styles to `nav__links` to be more specific.
See the item 'EN' being mispaced:
> Fix Navigation Item Centering

- layouts/partials/sidebar.html
makes the sidebar url follow the baseURL option in the config.toml. if
baseURL is configured as "https://domain.tld/blog", `<a href="/">` points
to "https://domain.tld". This commit changes that behaviour so it points
to the baseURL; in the above example, it would be `<a href="/blog">`.
> fix: sidebar url

- layouts/partials/footer.html
Since the site variables are passed with the key `context` in a dictionary, the if condition `.Site.Params.gtagId` should be modified to `.context.Site.Params.gtagId` to check the gtagId properly.
Related to issue #228.
> fix: if condition with gtagId

- README.md
- exampleSite/config/_default/config.toml
- exampleSite/content/english/post/series-part-1.md
- exampleSite/content/english/post/series-part-2.md
- layouts/_default/single.html
- layouts/partials/series.html
This merge request is based on the issue #234 
I've added the following things to make the series work in the theme:
- Example site: Add 2 blog posts which are part of the same series, these also describe how it works
- Config: Add the series taxonomy
- README: Add the section on how to enable series
- layouts/partials/series.html: Add a new partial to display all the posts in the series.
- layouts/_default/single.html: Introduce the new partial that will show the `Posts in this series`
I've tested the functionality with the 2 example site blog posts.
Since there is no real style guide I was unsure where to place the functionality inside the single so I added it where I think it fits best. Let me know if you would like it in a different location!
I also noticed the Table of Contents is …
> Adding series to the theme

- assets/css/style.css
- layouts/partials/navbar.html
Needs more CSS styling and maybe JS to handle dropdown
Closes #169
> Language dropdown

- assets/css/style.css
@lxndrblz sorry about the multiple pull requests! Hopefully this is one of the last ones regarding the dropdown.
Before:
After:
Actually for the second commit is there a reason for the 5px padding on the left? Please let me know if I'm missing anything here and I'll drop the commit.
> fix: language dropdown styling

- layouts/partials/head.html
Currently, the canonical link is set relative to the page root which is a major [SEO issue](https://web.dev/canonical/?utm_source=lighthouse&utm_medium=devtools).
```
<link rel="canonical" href="{{ .RelPermalink }}" />
```
This PR fixes this and brings the lighthouse score back on track. :dash:
> Make Canoncial Link Absolute

- .gitignore
As I, and maybe others too, like developing in VSCode Devcontainers, I added the folder to `.gitignore`.
I guess it makes even more sense to ignore than to share `.devcontainer` allowing each user have their own local configuration.
> Add .devcontainer directory to gitignore

- assets/css/style.css
I found the styling of the language picker on mobile to be odd. This PR reworks this.
before:
after:
> Fix Language Picker Styling on Mobile

- README.md
- exampleSite/config/_default/params.toml
- layouts/partials/head.html
This PR enables to switch the page title to be: `PageTitle | Autor` instead of the default `Author | PageTitle`
> feat: Added page title switcher

- README.md
- exampleSite/config/_default/config.toml
- exampleSite/go.mod
- go.mod
This PR turns the theme into a hugo module.
With `git`and `go` installed, making use of the anatole theme is now as easy as:
```
hugo new site my_site
cd mysite
echo 'theme = "github.com/lxndrblz/anatole"' >> config.toml
hugo server
```
Copying/cloning the theme in the themes folder is still possible of course.
If desired, I can extend the `Quickstart` section in `README.md`, explaining how to make use of the theme as module.
> Turn anatole theme into a hugo module

- layouts/_default/baseof.html
When ```displayMode = "dark"``` is set in ```params``` the dark theme is still not the preferred.
- #318 
---
---
The fix is so small. But I have checked it works.
---
- [Yes] Desktop Light Mode (Default)
- [Yes] Desktop Dark Mode
- [Yes] Desktop Light RTL Mode
- [Yes] Desktop Dark RTL Mode
- [ Yes] Mobile Light Mode
- [Yes] Mobile Dark Mode
- [Yes] Mobile Light RTL Mode
- [Yes] Mobile Dark RTL Mode
---
- @lxndrblz
> fix: [display] dark mode preference was not taken into account.

- layouts/partials/head.html
Currently, Open Graph is only set when the `series` taxonomy is used. This is an inopportune default which this PR addresses.
Citing @Xen-Echo from #166:
> Testing locally the open graph template only fails to render if you have pages with "series" front matter and haven't also specified the corresponding "series" taxonomy. I personally don't think this should stop the open graph template rendering though as you lose the basic open graph fields like image etc. when you copy a page link somewhere that supports rich URLs.
Whoever sets `series` in front mattter configs without having the `series` taxonomy enabled in the site configuration should not be 'protected'.
#166
---
Checklist
---
Yes, I ensured that all of the following scenarios …
> Set open graph meta tags without requiring series taxonomy

- layouts/index.html
Fixes an issue where the post summary would appear as unstyled on the front page.
Before:
After:
- N/A
---
---
---
---
> fix: non styled summary

- exampleSite/data/portfolio.yml
- layouts/portfolio/list.html
Hi!
I've prepared some suggestions for improvements of the portfolio feature:
* automatic generator of id attributes to enable support for anchor links for portfolio categories
* allow for customization of the `portfolioitem` links by adding new attribute `linktext` which can override the default `"Visit Site"` text
* generate links for a `portfolioitem` only when the `link` attribute is not empty
So far this PR does not contain tests, documentation or an example. Any suggestions are welcome!
Ondrej
n/a
---
n/a
---
---
---
@lxndrblz
> feat: layout improvements for portfolio

- layouts/partials/footer.html
Issue with Google Analytics v4 token. Hugo provides a separate internal template for v4 token which can be identified by their Prefix (v3 `UA-XXXXXXX-X` and v4 `G-XXXXXXXX`). 
I added an if-clause to check the prefix of googleAnalytics variable for v4 format. Loading according internal template as specified in hugo docs.
[Google Analytics v4 requires different internal Template than currently used \#339](https://github.com/lxndrblz/anatole/issues/339)
---
---
---
> fix: loading the correct internal Google Analytics template for v4 token

- layouts/_default/rss.xml
RSS considers content or summary as `<description></>` and ignores descriptions supplied in post front matters. This PR changes this to prefer front matter descriptions over summaries.  
#340 
---
---
> Use front matter description as rss item description

- layouts/partials/sidebar.html
Removes the duplicate H1 tag in the sidebar to improve SEO scores.
- Closes #345 
---
---
---
---
> fix: remove double h1 tags

- layouts/partials/sidebar.html
Hello,
I was testing your theme and one thing that annoyed me was the fact that the links to the socials didn't open on a new tab. Add this, not sure if you want to merge it.
Regards,
Renato.
Clicking on the social icons opens on the same blog page.
---
---
---
---
@lxndrblz
> open social links on a new tab

- layouts/partials/schema.html
The quotes are escaping the title text, which is making the ld+json parsing failing.
ex: "John's blog" will be converted to "John\x27s Blog" which is not parsable as ld+json. 
Discovered using Google search console (https://search.google.com/) SEO analyse. 
Error:"Unparsable structured data > Bad escape sequence in string"
Ref: https://support.google.com/webmasters/answer/9166415#error_types
---
This seems to be a common hugo problem, for me this solution solved it. 
I saw the | jsonify | safeJS options on the thread: https://github.com/gohugoio/hugo/issues/8386
---
---
---
@lxndrblz
> the quotes wrapping the variables are escaping the title text

- exampleSite/config/_default/params.toml
- i18n/it.toml
- layouts/partials/contact.html
I added reCAPTCHA to Form Spree.
As the introduced changes are very few, I did not create an issue. However, let me know if it's still mandatory.
---
Maybe I could add some documentation about adding reCAPTCHA to the contact form. Personally, I used [this tutorial](https://bogdanworks.com/post/formspree-contact-form/) and it worked fine. Where can I do that?
---
---
---
@lxndrblz
> Added reCAPTCHA to the contact form

- layouts/partials/sidebar.html
[rel="me"] is a commonly used way to show that that two websites or social media accounts are the same, and is used for authentication and proving site ownership in a variety of ways.
[rel="me"]: https://indieweb.org/rel-me
_Describe the issue fixed here_
---
---
_not applicable_
---
_n/a_
---
> Adds rel-me to social links

- exampleSite/config/_default/params.toml
- layouts/partials/analytics/umami.html
Umami provides support to assign a custom name to the tracker script different from the default `umami.js` (`TRACKER_SCRIPT_NAME` environment variable) to help you avoid some ad-blockers: https://umami.is/docs/environment-variables
I have added support in Anatole to check if `trackerScriptName` is provided then use it, if not then keep using default `umami.js` as before.
Wiki documentation must be updated for the same.
No issue created.
---
---
---
---
@lxndrblz
> feat: add support to provide custom tracker script name for Umami Analytics

- assets/css/markupHighlight.css
When switching to the dark theme, some code blocks become unreadable.
Regarding this [post](https://anatole-demo.netlify.app/post/notice-shortcode/) in the example site.
No issue was created for this PR.
---
Yes, I included all necessary artifacts, including:
---
---
@lxndrblz
> Fix font color bug when switching to dark theme

- assets/scss/partials/components/_post.scss
Fixes an issue where overly long list items would cause the viewport to extend too far horizontally.
#496
---
---
---
---
- @ericswpark
> fix: wordwrap in (un)ordered list

- layouts/partials/footer.html
Removes the deprecated asnc version of Google Analytics.
- #493
---
---
---
---
- @McPringle
> fix: remove async version of Google Analytics

- layouts/partials/head.html
The character encoding must appear in the first 1,024 bytes - https://html.spec.whatwg.org/multipage/semantics.html#charset
The `<meta>` and `<link>` elements are self closing. No need for a trailing `/`
* https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names
* https://html.spec.whatwg.org/multipage/semantics.html#the-link-element
#477
---
---
---
> Tidy <head> elements

- .prettierrc
In recent version the autodiscovery of Prettier is no longer supported.
See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
---
---
---
---
> chore: explicitly list prettier plugins

- assets/scss/partials/components/_post.scss
Code blocks created via backticks wrap all content like in the screenshot below:
The suggested change removes the brackets around the rendered content like so:
> fix: remove decoration around backtick blocks

- i18n/ar.toml
- i18n/de.toml
- i18n/dk.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fa.toml
- i18n/fi.toml
- i18n/fr.toml
- i18n/hu.toml
- i18n/id.toml
- i18n/it.toml
- i18n/ja.toml
- i18n/ko.toml
- i18n/pt-PT.toml
- i18n/pt-br.toml
- i18n/tr.toml
- i18n/zh-cn.toml
- i18n/zh-tw.toml
- layouts/partials/related.html
The "Related Posts" text is currently not considered for translation. I have added the german translation as well as the i8n function call.
#472 
---
---
---
> feat: translate related posts header

- assets/scss/partials/components/_sidebar.scss
- layouts/partials/sidebar.html
I noticed the home page side bar was repositioning items slightly when I moved from the home page to others. I had trouble finding the issue but realized it was the title (sidebar__introduction-title). On the homepage it's a h1 object and on others it's a div. I assume this is for SEO.
Both the H1 and DIV have the same CSS and same class - and even though they have the same margin of 1em, something is causing their margins to be computed differently. (For me h1 is 24px and div is 16pix). 
A workaround for this was to keep both in a div with the same class, however when it's the home page wrap the a element in a h1 element while still keeping the div. I made sure the CSS styling removes the h1 elements margin while existing within the div too.
This keeps the positioning of sidebar objects …
> fix: Sidebar Title Changing Margin Size Between Home Page and Others

- exampleSite/config/_default/languages.toml
When running exampleSite with hugo 0.113.0, a warning is displayed:
```
WARN 2023/06/07 22:15:10 config: languages.ar.description:
custom params on the language top level is deprecated and
will be removed in a future release. Put the value below
[languages.ar.params].
See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
```
This PR fixes this issue.
> Fix warning when using hugo v0.112+

- layouts/portfolio/list.html
This pull request implements multilingual support for portfolio data.
Data for portfolio is looked at `data/<language-code>/portfolio.yml` first and if it doesn't exists, then we use `data/portfolio.yml` like before.
#397
I can add a spanish translation of the exampleSite and provide a working example if you want.
---
There's no porfolio example for RTL mode and I don't know how to test it.
---
> Implement multilingual portfolio data

- assets/scss/partials/components/_archive.scss
- layouts/_default/list.html
- layouts/_default/single.html
Users can set disableTitleCapitalization to true in order to, well, disable title capitalization.
Fixes #368
---
I wrote this on my phone so it may not work?
---
Documentation moved to wiki since I last contributed here, so once this PR is merged I guess the wiki could be edited?
---
---
- @McPringle
- @lxndrblz
> feat: add config option to disable title capitalization

- .github/workflows/format.yml
- .github/workflows/update-resources.yml
- netlify.toml
This PR bumps GitHub action workflows, thus avoiding deprecation warnings as seen e.g. [here](https://github.com/lxndrblz/anatole/actions/runs/10130511700).
> Bump GitHub action workflows

- exampleSite/config/_default/hugo.toml
- exampleSite/content/english/post/rich-content.md
When previewing example site with latest hugo version 0.144.2, warnings are shown, e.g.:
```
WARN  The "twitter", "tweet", and "twitter_simple" shortcodes were deprecated in v0.142.0 and will be removed in a future release.
Please use the "x" shortcode instead.
```
This PR fixes these warnings.
> fix: clear warnings when previewing example site (hugo 0.144.2)

- assets/js/anatole-theme-switcher.js
Currently, when the theme is set to be either light or dark, and the browser's option is changed, it results in the theme being inverted with what is wanted (i.e. setting light theme results in dark theme, and vice versa). With this change, the theme switcher works as expected.
---
---
> Fix theme switcher

- layouts/index.html
Replacing `markdownify` to `safeHTML` introduced a regression. 
`markdownify` removes tags like h, a, multiple p, and returns one paragraph with plain html.
`safeHTML` returns full html with h, a multiple p.
Adding `plainify` makes output the same like with `markdownify`.
> Fix regression by planify post content on index

- layouts/partials/analytics/meta.html
- layouts/partials/head.html
Add support for Meta (Facebook) Pixel tracker.
- #539
---
To use Meta Pixel Analytics, include the following section and change the `pixelId` to the the Id of the Pixel for your domain.
```toml
[params.meta]
pixelId = 111111111111111
```
---
---
---
- @lxndrblz
> Add support for Meta Pixel tracker

- .devcontainer/devcontainer.json
- .github/workflows/update-resources.yml
- .gitignore
- assets/scss/anatole.rtl.scss
- assets/scss/anatole.scss
- assets/scss/main.scss
- assets/scss/modules/_variables.scss
- assets/scss/partials/components/_wrapper.scss
- exampleSite/config/_default/languages.toml
- exampleSite/config/_default/params.toml
- layouts/partials/head.html
- netlify.toml
As reported in #550, the site wide configuration setting `contentratio` does not work any more. This PR fixes that issue.
This PR closes #550.
With this PR applied, Sass variables are now initialize from Hugo templates in a modern, clean way. This way is described in this [discussion thread](https://discourse.gohugo.io/t/initialize-sass-variables-from-hugo-templates/42053#the-new-way-2) on hugo's discourse system.
---
> fix: make setting 'contentratio' work again
