lxndrblz/anatole

- README.md
> README: document the CSP compliance aspect

- assets/css/style.css
- layouts/partials/navbar.html
- layouts/partials/sidebar.html
- Set aria-label correctly for screen readers to work
- Use fa-2x size for social icons
> Adjust social icon size and resolve lighthouse issues

- layouts/partials/navbar.html
> Buggy menu

- assets/css/style.css
- assets/js/anatole-header.js
- layouts/_default/baseof.html
- layouts/partials/head.html
This commit fixes problems presented in #21 and the original problems presented in #14.
> Bug fixes for theme switching

- layouts/partials/footer.html
- layouts/partials/head.html
- layouts/partials/medium-zoom.html
> Add  "crossorigin=anonymous" to scripts that have an integrity attribute

- assets/css/style.css
- layouts/partials/head.html
> 🗂 Fixes wrong links in footnotes

- layouts/partials/head.html
this enables the appropriate rel links for RSS feeds
> enable RSS metadata

- assets/css/style.css
The original gray colour seems too bright in the dark mode. Therefore, switch it to a darker colour.
> Improve dark mode theming

- i18n/fa.toml
The title is clear.
Added Persian support to it.
> Added fa.toml to i18n for Persian language support

- README.md
- exampleSite/config.toml
- layouts/partials/head.html
- layouts/partials/sidebar.html
This changes affect mainly:
- Check `exampleSite/config.toml` to see the new paradigm. Make sure to modify your `config.toml` accordingly. 
- `layouts/partial/head.html`, changing the source of the icons
- `layouts/partial/sidebar.html`, to adapt to new syntax.
> Updating to FontAwesome 5.15.1 icons

- i18n/dk.toml
Added a DK (Danish) language option.
Hope it's useful.
> added dk language

- i18n/zh-zn.toml
> Fix a tiny detail

- README.md
- layouts/partials/head.html
Adding open graph tags to the template to improve SEO of sites using it.
https://gohugo.io/templates/internal/#use-the-open-graph-template
> Add open graph tags

- README.md
- layouts/partials/footer.html
- layouts/partials/google-analytics-gtag-async.html
Creating pull request as per: [Request 148](https://github.com/lxndrblz/anatole/issues/148)
> Adding support for Google Analytics 4.

- README.md
- exampleSite/config.toml
- i18n/de.toml
- i18n/dk.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fa.toml
- i18n/fi.toml
- i18n/fr.toml
- i18n/it.toml
- i18n/pt-br.toml
- i18n/zh-cn.toml
- i18n/zh-tw.toml
- layouts/index.html
This adds '...Read more' link to each truncated post listed on Home Page.
> add feature readmore in index.html

- i18n/kr.toml
(please let me know if I missed any other files that need to be translated!)
> Add Korean translation

- README.md
> Fix config sample link

- README.md
* Added socials documentation to the modifying the config.toml section of the readme
> Update README to contain socials

- README.md
- assets/css/style.css
- assets/css/style.rtl.css
- layouts/partials/head.html
Make width of sidebar and content customized
> Add customize able sidebar

- assets/css/style.css
- assets/css/style.rtl.css
- assets/js/medium-zoom.js
> Fix cloudflare minification

- assets/css/style.css
- assets/css/style.rtl.css
> Set the height of the profile image explicitly

- README.md
- layouts/_default/rss.xml
Changes:
- README has more information on RSS configuration
- Added option to show full page content in the RSS feed
Closes #203
> RSS improvements

- .github/workflows/format.yml
To enforce a consistent formatting of the `master` branch, I propose this GitHub Action.
> Add Prettier Format Action

- README.md
- layouts/_default/single.html
This PR enables a TOC to be automatically generated on a per post basis by adding toc=true into the front matter of a post.
> add a toc on a per post basis

- assets/css/style.css
- layouts/index.html
- layouts/partials/pagination.html
> prettier pagination

- README.md
- exampleSite/config/_default/params.toml
- layouts/partials/head.html
I wanted support for a different font, so I added Google Fonts support. Not sure how much this impacts the `100/100` Google Lighthouse score but it should be marginal.
> Add support for Google Fonts

- assets/css/style.css
> fix: overlap on ultra wide screens

- layouts/partials/pagination.html
i don't know if any other language than english is "understood" by the programs "reading" aria-label - if so this should be added as translation to the i18n files.
> added english aria labels for prev/next

- README.md
I just checked my module PR, everyting works as expected. While doing so, I realized that adding a few links might help to get started easier, here comes the PR.
> README.md: adding links to config .toml and example site

- .github/PULL_REQUEST_TEMPLATE.md
kindly do tell me if any section needs to be added.
> created a PULL_REQUEST_TEMPLATE.md

- README.md
- exampleSite/config/_default/params.toml
- layouts/partials/analytics/plausible.html
- layouts/partials/head.html
Adds an option to use Plausible Analytics.
> Add option to use Plausible Analytics

- README.md
- exampleSite/config/_default/params.toml
- layouts/partials/analytics/umami.html
- layouts/partials/head.html
This PR adds the ability to integrate the self-hosted Umami Analytics.
> Add Umami analytics

- .github/CONTRIBUTING.md
- README.md
Adds a contribution guideline to the project.
Closes #280
---
N.A.
---
Yes, I included all necessary artifacts, including:
---
---
> docs: add contributing.md

- layouts/index.html
- layouts/partials/navbar.html
Fixes the errors indicated by the W3C validator.
#309
---
---
---
---
> fix: w3c validator errors

- .commitlintrc.json
- .github/CONTRIBUTING.md
- .husky/commit-msg
- .release-it.json
- README.md
- package-lock.json
- package.json
Currently, releases are handled manually and there is no local tracking of `CHANGELOG.md`. We can improve things by adding [release-it](https://github.com/release-it/release-it) and enforcing complyment with the commit guidelines of [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
---
---
Test scenarios do not apply.
> Add release-it and Conventional Commits compliance

- layouts/partials/head.html
This PR adds a meta author HTML tags in the header:
```html
<meta name="author" content="{{ .Site.Params.author }}">
```
NA
---
---
---
- @lxndrblz
> new: [layouts] added meta author HTML tag.

- README.md
- exampleSite/config/_default/params.toml
- layouts/_default/_markup/render-codeblock-mermaid.html
- layouts/_default/single.html
- layouts/partials/mermaid.html
https://gohugo.io/content-management/diagrams/#mermaid-diagrams
Mermaid JS library provides the ability to create markdown-based diagrams and charts within your Hugo markdown.
This PR provides the ability for a user to include those diagrams in their posts, pages, etc.
n/a
---
---
- [X ] Implementation (Code and Ressources)
---
---
@jforman
> add mermaid support for making diagrams

- i18n/it.toml
I fixed an Italian word that sounded weird to me and added some punctuation.
No issue was created for this PR. 
---
---
---
@lxndrblz
> Italian translation fix

- package-lock.json
- package.json
Bumps the release-it version to resolve a security vulnerability within the got package.
---
---
---
---
> chore: bump release-it version

- exampleSite/config/_default/config.toml
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/index.html
New feature: localized dates
If `params.localizedDates = true`, then single date, index date, and list date will be localized.
Using `params.localizedDates = true` requires Hugo version 0.87.0 or above.
---
---
---
> New feature: localized dates

- package-lock.json
- package.json
Fixes a vulnerability inside the vm2 package.
---
---
---
---
> chore: bump npm package versions

- package-lock.json
- package.json
Fixes an error with the prettier code formater.
---
---
---
---
> fix: prettier error with go template

- i18n/id.toml
The Indonesia language is added. All parameters are translated into the native Indonesia language.
---
---
---
---
> feat: add id.toml

- i18n/hu.toml
Adds Hungarian localization
---
---
---
---
- @lxndrblz
> feat: add Hungarian localization

- .github/workflows/format.yml
- .github/workflows/update-resources.yml
This PR updates the Node.js and Hugo version.
> chore: update node and hugo version

- package-lock.json
Bumps the npm versions to resolved known vulnerabilities.
Closes #450 
---
---
---
---
> chore: Bump NPM Versions

- package-lock.json
Updates 8 NPM packages.
---
---
---
---
> chore: bump npm version

- exampleSite/data/portfolio.yml
- layouts/portfolio/list.html
I added a description for the portfolio categories.
---
---
---
---
> feat: add descriptions to portfolio categories

- layouts/partials/analytics/matomo.html
- layouts/partials/head.html
Adds support for Matomo Analytics (formerly known as Piwik).
- #411
---
---
---
---
- @mrimann
> feat: add matomo analytics support

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
- package-lock.json
Updates the dependencies to the latest versions.
---
---
---
---
- @dependabot
> chore: update dependencies

- .devcontainer/Dockerfile
- exampleSite/config/_default/config.toml
- exampleSite/content/english/post/rich-content.md
- layouts/_default/single.html
- layouts/partials/footer.html
- netlify.toml
Close #465 and other deprecation warnings 
---
---
---
---
> fix: deprecation warnings for recent Hugo versions

- CHANGELOG.md
- assets/scss/partials/vendors/_table.scss
- layouts/_default/list.html
Format files with prettier.
---
---
---
---
> chore: run prettier

- .husky/commit-msg
- package-lock.json
- package.json
This PR bumps npm dependencies to their latest versions.
> Bump npm dependencies

- exampleSite/config/_default/params.toml
- layouts/index.html
Adds the option to disable the title capitalisation on the index page.
- Close #516 
---
---
---
---
> feat: add option to disable title capitalization on index

- exampleSite/config/_default/hugo.toml
- layouts/_default/rss.xml
- layouts/index.html
Fixes an issue where the summary would not render.
- Close #529
---
---
---
---
> fix: unsafe HTML error in summary

- .devcontainer/devcontainer.json
- package-lock.json
Updates dev container and node dependencies.
---
---
---
---
> chore: update dev dependencies

- layouts/_default/rss.xml
Fixes a broken RSS feed reported.
Close #534 
---
---
---
---
> fix: broken rss stream

- netlify.toml
- package-lock.json
Updates the NPM packages to the latest version.
- 
---
- 
---
---
---
> chore: update NPM packages

- exampleSite/config/_default/hugo.toml
- exampleSite/content/english/post/mermaid-test.md
- layouts/partials/mermaid.html
- netlify.toml
- package-lock.json
- package.json
Retrieves the theme and uses it to initialise Mermaid with a theme.
---
No idea how to redraw mermaid if the theme is changed while it is displayed.  A page refresh will update mermaid.
---
---
---
> feat: update Mermaid Diagrams to follow theme preference
